export const vehicles = [
  {
    id: 1,
    name: "Ferrari 458 Italia",
    category: "sports",
    price: 299,
    image: "/placeholder.svg?height=400&width=600&text=Ferrari+458+Italia",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Ferrari+458+Italia+Front",
      "/placeholder.svg?height=400&width=600&text=Ferrari+458+Italia+Side",
      "/placeholder.svg?height=400&width=600&text=Ferrari+458+Italia+Interior",
      "/placeholder.svg?height=400&width=600&text=Ferrari+458+Italia+Back",
    ],
    description:
      "Experience the thrill of Italian engineering with this stunning Ferrari 458 Italia. Perfect for special occasions and unforgettable drives through scenic routes with unmatched performance, luxury, and cutting-edge technology.",
    longDescription:
      "The Ferrari 458 Italia represents the pinnacle of Italian automotive excellence. With its naturally aspirated V8 engine producing 570 horsepower, this masterpiece delivers an exhilarating driving experience that few cars can match. The aerodynamic design isn't just beautiful—it's functional, providing optimal downforce and cooling. Every detail, from the carbon fiber accents to the hand-stitched leather interior, reflects Ferrari's commitment to perfection. Whether you're cruising through city streets or carving through mountain roads, the 458 Italia transforms every journey into an unforgettable adventure.",
    features: ["2 Seats", "Manual", "V8 Engine", "RWD", "Carbon Fiber", "Sport Mode"],
    specifications: {
      engine: "4.5L V8 Naturally Aspirated",
      power: "570 HP @ 9,000 RPM",
      torque: "398 lb-ft @ 6,000 RPM",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "Rear-Wheel Drive",
      acceleration: "0-60 mph in 3.4 seconds",
      topSpeed: "202 mph",
      fuelEconomy: "13/18 mpg (city/highway)",
    },
    amenities: [
      "Premium Leather Interior",
      "Carbon Fiber Dashboard",
      "Racing Seats",
      "Premium Sound System",
      "Climate Control",
      "Navigation System",
      "Bluetooth Connectivity",
      "USB Charging Ports",
    ],
    rating: 4.9,
    reviews: 127,
    reviewsData: [
      {
        id: 1,
        name: "Michael Rodriguez",
        rating: 5,
        date: "2024-01-15",
        comment:
          "Absolutely incredible experience! The Ferrari 458 Italia exceeded all my expectations. The sound of that V8 engine is pure music.",
      },
      {
        id: 2,
        name: "Sarah Johnson",
        rating: 5,
        date: "2024-01-10",
        comment:
          "Perfect for our anniversary celebration. The car handled beautifully and turned heads everywhere we went. Highly recommended!",
      },
      {
        id: 3,
        name: "David Chen",
        rating: 4,
        date: "2024-01-05",
        comment:
          "Amazing performance and stunning looks. The only minor issue was the firm suspension, but that's expected in a sports car.",
      },
    ],
  },
  {
    id: 2,
    name: "Ford F-150 Raptor",
    category: "truck",
    price: 199,
    image: "/placeholder.svg?height=400&width=600&text=Ford+F-150+Raptor",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Ford+F-150+Raptor+Front",
      "/placeholder.svg?height=400&width=600&text=Ford+F-150+Raptor+Side",
      "/placeholder.svg?height=400&width=600&text=Ford+F-150+Raptor+Interior",
      "/placeholder.svg?height=400&width=600&text=Ford+F-150+Raptor+Bed",
    ],
    description:
      "Conquer any terrain with this powerful and capable Ford F-150 Raptor. Built for adventure and heavy-duty performance in any condition, perfect for off-road enthusiasts and professional work applications.",
    longDescription:
      "The Ford F-150 Raptor is the ultimate off-road pickup truck, engineered to tackle the most challenging terrains with confidence. Its high-output EcoBoost V6 engine delivers impressive power while maintaining efficiency. The advanced suspension system with Fox Racing Shocks provides exceptional off-road capability and on-road comfort. With its rugged exterior design, spacious interior, and advanced technology features, the Raptor is equally at home on construction sites, mountain trails, or city streets. This truck doesn't just transport you—it empowers you to explore beyond the beaten path.",
    features: ["5 Seats", "Automatic", "V6 Turbo", "4WD", "Off-Road Package", "Tow Package"],
    specifications: {
      engine: "3.5L V6 EcoBoost Twin-Turbo",
      power: "450 HP @ 5,700 RPM",
      torque: "510 lb-ft @ 3,500 RPM",
      transmission: "10-Speed Automatic",
      drivetrain: "4-Wheel Drive",
      acceleration: "0-60 mph in 5.1 seconds",
      topSpeed: "107 mph",
      towingCapacity: "8,200 lbs",
      payloadCapacity: "1,400 lbs",
    },
    amenities: [
      "Leather-Appointed Seats",
      "SYNC 4 Infotainment",
      "12-Inch Touchscreen",
      "Bang & Olufsen Audio",
      "Dual-Zone Climate Control",
      "Wireless Charging Pad",
      "Multiple USB Ports",
      "110V Power Outlet",
    ],
    rating: 4.7,
    reviews: 89,
    reviewsData: [
      {
        id: 1,
        name: "Jake Thompson",
        rating: 5,
        date: "2024-01-12",
        comment:
          "Perfect for our camping trip! The Raptor handled rocky trails like a champ and had plenty of space for all our gear.",
      },
      {
        id: 2,
        name: "Lisa Martinez",
        rating: 4,
        date: "2024-01-08",
        comment:
          "Great truck for work and play. The towing capacity is impressive and the interior is surprisingly comfortable.",
      },
    ],
  },
  {
    id: 3,
    name: "Mercedes-Benz A-Class",
    category: "luxury",
    price: 149,
    image: "/placeholder.svg?height=400&width=600&text=Mercedes+A-Class",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Mercedes+A-Class+Front",
      "/placeholder.svg?height=400&width=600&text=Mercedes+A-Class+Side",
      "/placeholder.svg?height=400&width=600&text=Mercedes+A-Class+Interior",
      "/placeholder.svg?height=400&width=600&text=Mercedes+A-Class+Dashboard",
    ],
    description:
      "Enjoy premium comfort and advanced technology in this elegant Mercedes-Benz A-Class. Perfect for business meetings, luxury travel, and sophisticated city driving with state-of-the-art features.",
    longDescription:
      "The Mercedes-Benz A-Class redefines what a compact luxury sedan can be. With its sleek exterior design and meticulously crafted interior, this vehicle offers a premium experience in every detail. The advanced MBUX infotainment system responds to natural voice commands, while the turbocharged engine provides smooth, efficient performance. Safety features like Active Brake Assist and Attention Assist ensure peace of mind on every journey. Whether you're navigating busy city streets or cruising on the highway, the A-Class delivers the perfect blend of luxury, technology, and performance that Mercedes-Benz is renowned for.",
    features: ["5 Seats", "Automatic", "Turbo", "FWD", "MBUX System", "Premium Audio"],
    specifications: {
      engine: "2.0L 4-Cylinder Turbo",
      power: "188 HP @ 5,800 RPM",
      torque: "221 lb-ft @ 1,600 RPM",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "Front-Wheel Drive",
      acceleration: "0-60 mph in 7.1 seconds",
      topSpeed: "144 mph",
      fuelEconomy: "24/35 mpg (city/highway)",
    },
    amenities: [
      "MB-Tex Upholstery",
      "MBUX Infotainment",
      "10.25-inch Display",
      "Burmester Audio System",
      "Dual-Zone Climate Control",
      "Ambient Lighting",
      "Wireless Phone Integration",
      "Voice Control",
    ],
    rating: 4.8,
    reviews: 156,
    reviewsData: [
      {
        id: 1,
        name: "Robert Wilson",
        rating: 5,
        date: "2024-01-14",
        comment:
          "Excellent luxury sedan for business trips. The MBUX system is intuitive and the ride quality is superb.",
      },
      {
        id: 2,
        name: "Emma Davis",
        rating: 5,
        date: "2024-01-09",
        comment: "Love the elegant design and advanced features. Perfect for city driving with great fuel economy.",
      },
    ],
  },
  {
    id: 4,
    name: "Jeep Renegade",
    category: "suv",
    price: 129,
    image: "/placeholder.svg?height=400&width=600&text=Jeep+Renegade",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Jeep+Renegade+Front",
      "/placeholder.svg?height=400&width=600&text=Jeep+Renegade+Side",
      "/placeholder.svg?height=400&width=600&text=Jeep+Renegade+Interior",
      "/placeholder.svg?height=400&width=600&text=Jeep+Renegade+Cargo",
    ],
    description:
      "Adventure awaits with this versatile and rugged Jeep Renegade. Ideal for city driving and weekend getaways with friends and family, offering the perfect blend of comfort, capability, and reliability.",
    longDescription:
      "The Jeep Renegade brings authentic Jeep capability to the compact SUV segment. With its distinctive design and Trail Rated 4x4 capability, this vehicle is ready for both urban adventures and off-road excursions. The spacious interior offers flexibility with fold-flat rear seats and numerous storage solutions. Advanced safety features and the user-friendly Uconnect system keep you connected and protected. Whether you're commuting to work, exploring mountain trails, or loading up for a weekend camping trip, the Renegade adapts to your lifestyle with rugged dependability and surprising refinement.",
    features: ["5 Seats", "Automatic", "4-Cylinder", "AWD", "Trail Rated", "Uconnect"],
    specifications: {
      engine: "2.4L 4-Cylinder MultiAir",
      power: "180 HP @ 6,400 RPM",
      torque: "175 lb-ft @ 3,900 RPM",
      transmission: "9-Speed Automatic",
      drivetrain: "All-Wheel Drive",
      acceleration: "0-60 mph in 8.7 seconds",
      topSpeed: "112 mph",
      fuelEconomy: "22/30 mpg (city/highway)",
      groundClearance: "8.7 inches",
    },
    amenities: [
      "Cloth Upholstery",
      "Uconnect 4C NAV",
      "8.4-inch Touchscreen",
      "Alpine Audio System",
      "Manual Climate Control",
      "Removable Roof Panels",
      "Bluetooth Connectivity",
      "USB Ports",
    ],
    rating: 4.6,
    reviews: 203,
    reviewsData: [
      {
        id: 1,
        name: "Chris Anderson",
        rating: 5,
        date: "2024-01-11",
        comment:
          "Perfect family SUV! Great for both city driving and our weekend camping adventures. Kids love the removable roof panels.",
      },
      {
        id: 2,
        name: "Maria Garcia",
        rating: 4,
        date: "2024-01-07",
        comment:
          "Reliable and versatile. The AWD system gives confidence in all weather conditions. Good value for money.",
      },
    ],
  },
  {
    id: 5,
    name: "BMW X5",
    category: "luxury",
    price: 249,
    image: "/placeholder.svg?height=400&width=600&text=BMW+X5",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=BMW+X5+Front",
      "/placeholder.svg?height=400&width=600&text=BMW+X5+Side",
      "/placeholder.svg?height=400&width=600&text=BMW+X5+Interior",
      "/placeholder.svg?height=400&width=600&text=BMW+X5+Cargo",
    ],
    description:
      "Experience luxury and performance combined in this sophisticated BMW X5. Perfect for family trips, executive travel, and those who demand the finest in automotive excellence with premium comfort and advanced technology.",
    longDescription:
      "The BMW X5 sets the standard for luxury SUVs with its perfect balance of performance, comfort, and versatility. The powerful turbocharged engine delivers exhilarating acceleration while maintaining impressive efficiency. The spacious three-row seating accommodates up to seven passengers in premium comfort. Advanced driver assistance features and the intuitive iDrive system enhance both safety and convenience. With its commanding presence, refined interior, and dynamic driving characteristics, the X5 is equally suited for school runs, business meetings, or weekend getaways. This is luxury redefined for the modern family.",
    features: ["7 Seats", "Automatic", "V6 Turbo", "AWD", "iDrive", "Panoramic Roof"],
    specifications: {
      engine: "3.0L 6-Cylinder Twin-Turbo",
      power: "335 HP @ 5,500 RPM",
      torque: "330 lb-ft @ 1,500 RPM",
      transmission: "8-Speed Automatic",
      drivetrain: "All-Wheel Drive",
      acceleration: "0-60 mph in 5.3 seconds",
      topSpeed: "155 mph",
      fuelEconomy: "21/26 mpg (city/highway)",
      towingCapacity: "7,200 lbs",
    },
    amenities: [
      "Vernasca Leather Seats",
      "iDrive 7.0 System",
      "12.3-inch Display",
      "Harman Kardon Audio",
      "4-Zone Climate Control",
      "Panoramic Sunroof",
      "Wireless Apple CarPlay",
      "Gesture Control",
    ],
    rating: 4.8,
    reviews: 94,
    reviewsData: [
      {
        id: 1,
        name: "Thomas Brown",
        rating: 5,
        date: "2024-01-13",
        comment:
          "Outstanding luxury SUV! The perfect combination of performance and comfort. Great for long family trips.",
      },
      {
        id: 2,
        name: "Jennifer Lee",
        rating: 5,
        date: "2024-01-06",
        comment:
          "Impressive technology and build quality. The third row is actually usable for adults. Highly recommend!",
      },
    ],
  },
  {
    id: 6,
    name: "Tesla Model Y",
    category: "electric",
    price: 189,
    image: "/placeholder.svg?height=400&width=600&text=Tesla+Model+Y",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Tesla+Model+Y+Front",
      "/placeholder.svg?height=400&width=600&text=Tesla+Model+Y+Side",
      "/placeholder.svg?height=400&width=600&text=Tesla+Model+Y+Interior",
      "/placeholder.svg?height=400&width=600&text=Tesla+Model+Y+Charging",
    ],
    description:
      "Drive into the future with this cutting-edge Tesla Model Y. Zero emissions, maximum technology, and incredible performance make this the perfect eco-friendly choice for environmentally conscious travelers.",
    longDescription:
      "The Tesla Model Y represents the future of automotive technology. This all-electric SUV combines zero-emission driving with cutting-edge technology and impressive performance. The minimalist interior features a large touchscreen that controls virtually every function, while the glass roof creates an open, airy feeling. With Autopilot capabilities and over-the-air updates, your Model Y continuously improves. The instant torque delivery provides thrilling acceleration, while the advanced battery technology offers impressive range. Charging is convenient with access to Tesla's extensive Supercharger network. Experience the future of driving with sustainable luxury.",
    features: ["5 Seats", "Automatic", "Electric", "AWD", "Autopilot", "Supercharging"],
    specifications: {
      motor: "Dual Motor All-Wheel Drive",
      power: "384 HP Combined",
      torque: "375 lb-ft Instant",
      transmission: "Single-Speed Fixed Gear",
      drivetrain: "All-Wheel Drive",
      acceleration: "0-60 mph in 4.8 seconds",
      topSpeed: "135 mph",
      range: "326 miles EPA estimated",
      chargingTime: "15 minutes (10-80% at Supercharger)",
    },
    amenities: [
      "Vegan Leather Seats",
      "15-inch Touchscreen",
      "Premium Audio System",
      "HEPA Air Filtration",
      "Heated Seats (All)",
      "Glass Roof",
      "Mobile Connectivity",
      "Over-the-Air Updates",
    ],
    rating: 4.9,
    reviews: 178,
    reviewsData: [
      {
        id: 1,
        name: "Alex Kim",
        rating: 5,
        date: "2024-01-16",
        comment:
          "Amazing electric SUV! The acceleration is incredible and the technology is years ahead. Love the environmental benefits too.",
      },
      {
        id: 2,
        name: "Rachel Green",
        rating: 5,
        date: "2024-01-04",
        comment:
          "Perfect for our eco-conscious family. The Autopilot feature makes long drives so much easier. Highly impressed!",
      },
    ],
  },
]
